---
name: Dist-Release
version: 0.0_2
author:
  - 'Yanick Champoux <yanick@cpan.org>'
abstract: manages the process of releasing a module
license: perl
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Dist-Release
  license: http://dev.perl.org/licenses/
  repository: git://github.com/yanick/dist-release.git
requires:
  CPAN::Uploader: 0
  Hash::Merge: 0
  IPC::Cmd: 0
  Moose: 0
  Moose::Policy: 0
  Readonly: 0
  Test::More: 0
  YAML: 0
  perl: 5.10.0
  version: 0
provides:
  Dist::Release:
    file: lib/Dist/Release.pm
    version: 0.0_2
  Dist::Release::Action:
    file: lib/Dist/Release/Action.pm
  Dist::Release::Action::CPANUpload:
    file: lib/Dist/Release/Action/CPANUpload.pm
  Dist::Release::Action::GenerateDistribution:
    file: lib/Dist/Release/Action/GenerateDistribution.pm
  Dist::Release::Action::Github:
    file: lib/Dist/Release/Action/Github.pm
  Dist::Release::Check:
    file: lib/Dist/Release/Check.pm
  Dist::Release::Check::Manifest:
    file: lib/Dist/Release/Check/Manifest.pm
  Dist::Release::Check::Manifest::Build:
    file: lib/Dist/Release/Check/Manifest/Build.pm
  Dist::Release::Check::VCS::WorkingDirClean:
    file: lib/Dist/Release/Check/VCS/WorkingDirClean.pm
  Dist::Release::Check::VCS::WorkingDirClean::Git:
    file: lib/Dist/Release/Check/VCS/WorkingDirClean/Git.pm
  Dist::Release::Step:
    file: lib/Dist/Release/Step.pm
  Dist::Release::Step::VCS:
    file: lib/Dist/Release/Step/VCS.pm
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
