---
name: Dist-Release
version: 0.0_1
author:
  - 'Yanick Champoux <yanick@cpan.org>'
abstract: manage the process of releasing a module
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Test::More: 0
  version: 0
provides:
  Dist::Release:
    file: lib/Dist/Release.pm
    version: 0.0_1
  Dist::Release::Action:
    file: lib/Dist/Release/Action.pm
  Dist::Release::Action::CPANUpload:
    file: lib/Dist/Release/Action/CPANUpload.pm
  Dist::Release::Check:
    file: lib/Dist/Release/Check.pm
  Dist::Release::Check::Manifest::Build:
    file: lib/Dist/Release/Check/Manifest/Build.pm
  Dist::Release::Check::VCS::WorkingDirClean:
    file: lib/Dist/Release/Check/VCS/WorkingDirClean.pm
  Dist::Release::Check::VCS::WorkingDirClean::Git:
    file: lib/Dist/Release/Check/VCS/WorkingDirClean/Git.pm
  Dist::Release::Step:
    file: lib/Dist/Release/Step.pm
  M::R::Action::DoSomething:
    file: lib/Dist/Release/Action/DoSomething.pm
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
